# Non-secret settings for the dev environment. Secrets are never set here:
# the DB password is generated by Terraform and stored only in SSM.
project     = "threetier"
environment = "dev"
owner       = "abdallah-elmalawany"
aws_region  = "us-east-1"

# Change to <your-github-user>/<repo> before the first apply.
github_repository = "abdallahelmalawany/three-tier-devops"

# Sandbox-friendly defaults (see README "Sandbox notes").
enable_nat_gateway = false
db_instance_class  = "db.t3.micro"
db_multi_az        = false

# KodeKloud playgrounds block creating an IAM OIDC provider: CI uses the
# playground access keys stored as GitHub secrets instead.
enable_github_oidc = false

# The playground also denies these actions; each switch skips the
# resource that needs it.
db_create_parameter_group = false # rds:CreateDBParameterGroup
log_retention_days        = 0     # logs:PutRetentionPolicy
enable_autoscaling        = false # application-autoscaling:TagResource
enable_log_metric_alarm   = false # logs:PutMetricFilter
tag_iam_policies          = false # iam:TagPolicy
enable_flow_logs          = false # ec2:CreateFlowLogs

# alert_email = "you@example.com"
