# Non-secret settings for the dev environment. Secrets are never set here:
# the DB password is generated by Terraform and stored only in SSM.
project     = "threetier"
environment = "dev"
owner       = "abdallah-elmalawany"
aws_region  = "us-east-1"

# Change to <your-github-user>/<repo> before the first apply.
github_repository = "abdallahelmalawany/three-tier-devops"

# Sandbox-friendly defaults (see README "Sandbox notes").
enable_nat_gateway = false
db_instance_class  = "db.t3.micro"
db_multi_az        = false

# KodeKloud playgrounds block creating an IAM OIDC provider: CI uses the
# playground access keys stored as GitHub secrets instead.
enable_github_oidc = false

# alert_email = "you@example.com"
